#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/host-tools/sed-host/sed-host.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/host-tools/sed-host/sed-host.mk.orig $FREETZ_SSL_HOME_PATH/make/host-tools/sed-host/sed-host.mk 2>/dev/null
