#!/bin/bash
source $I_MATIK_PATH/support/i-matik/i-matik_net.conf
sudo ifconfig $NETZWERK 192.168.178.50 netmask 255.255.255.0
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' "$I_MATIK_PATH/config/fritzbox/openssl_10/config_fritz$1_openssl_1_0_x_powerline" | awk -F'"' '{print $2}' | xargs)"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"

BOX_HOME="${1:0:2}xx"	# set box home folder
FREETZ_SSL_PATH="FREETZ_PATH_SSL_10"
FREETZ_SSL_HOME_PATH="${!FREETZ_SSL_PATH}/$BOX_HOME"
	
for PUSH_IMAGE_NAME in $FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$1/${1}*${FUD_COMMENT_BOX}*${FUD_COMMENT_SSL}.image; do # Whitespace-safe but not recursive.
$FREETZ_SSL_HOME_PATH/tools/./push_firmware $PUSH_IMAGE_NAME -cmd ftp
done
