#!/bin/bash
# i-matik
rm -f $FREETZ_SSL_HOME_PATH/make/mod/files/root/etc/default.mod/motd 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/mod/files/root/etc/default.mod/motd.orig $FREETZ_SSL_HOME_PATH/make/mod/files/root/etc/default.mod/motd 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh.orig $FREETZ_SSL_HOME_PATH/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

# packages
rm -f $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/imagemagick/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/imagemagick/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/imagemagick/imagemagick.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/imagemagick/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/leptonica/leptonica.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/leptonica/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/010-enforce-libpng12.leptonica.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/tiff/tiff.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/tiff/external.in.libs 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/tiff/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk.orig $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk.orig $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in.orig $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/imagemagick/Config.in.orig $FREETZ_SSL_HOME_PATH/make/imagemagick/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/imagemagick/external.files.orig $FREETZ_SSL_HOME_PATH/make/imagemagick/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/imagemagick/imagemagick.mk.orig $FREETZ_SSL_HOME_PATH/make/imagemagick/imagemagick.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/imagemagick/external.in.orig $FREETZ_SSL_HOME_PATH/make/imagemagick/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/imagemagick/patches/010-extra_flags.patch.orig $FREETZ_SSL_HOME_PATH/make/imagemagick/patches/010-extra_flags.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/leptonica.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/leptonica.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/Config.in.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/010-enforce-libpng12.leptonica.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/010-enforce-libpng12.leptonica.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/020-no_xtractprotos.leptonica.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/020-no_xtractprotos.leptonica.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/030-no_demo_code_in_lib.leptonica.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/leptonica/patches/030-no_demo_code_in_lib.leptonica.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/tiff/tiff.mk.orig $FREETZ_SSL_HOME_PATH/make/tiff/tiff.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/tiff/external.in.libs.orig $FREETZ_SSL_HOME_PATH/make/tiff/external.in.libs 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/tiff/Config.in.orig $FREETZ_SSL_HOME_PATH/make/tiff/Config.in 2>/dev/null
