#!/bin/bash
BOX_HOME="${1:0:2}xx"	# set box home folder
FREETZ_SSL_PATH10="FREETZ_PATH_SSL_10"
FREETZ_SSL_HOME_PATH10="${!FREETZ_SSL_PATH10}/$BOX_HOME"

FREETZ_SSL_PATH11="FREETZ_PATH_SSL_11"
FREETZ_SSL_HOME_PATH11="${!FREETZ_SSL_PATH11}/$BOX_HOME"

FREETZ_SSL_PATH30="FREETZ_PATH_SSL_30"
FREETZ_SSL_HOME_PATH30="${!FREETZ_SSL_PATH30}/$BOX_HOME"

rm -f $FREETZ_SSL_HOME_PATH10/make/mod/files/root/etc/default.mod/motd 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH10/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

mv $FREETZ_SSL_HOME_PATH10/make/mod/files/root/etc/default.mod/motd.orig $FREETZ_SSL_HOME_PATH10/make/mod/files/root/etc/default.mod/motd 2>/dev/null
mv $FREETZ_SSL_HOME_PATH10/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh.orig $FREETZ_SSL_HOME_PATH10/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

rm -f $FREETZ_SSL_HOME_PATH11/make/mod/files/root/etc/default.mod/motd 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH11/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

mv $FREETZ_SSL_HOME_PATH11/make/mod/files/root/etc/default.mod/motd.orig $FREETZ_SSL_HOME_PATH11/make/mod/files/root/etc/default.mod/motd 2>/dev/null
mv $FREETZ_SSL_HOME_PATH11/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh.orig $FREETZ_SSL_HOME_PATH11/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

rm -f $FREETZ_SSL_HOME_PATH30/make/mod/files/root/etc/default.mod/motd 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH30/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null

mv $FREETZ_SSL_HOME_PATH30/make/mod/files/root/etc/default.mod/motd.orig $FREETZ_SSL_HOME_PATH30/make/mod/files/root/etc/default.mod/motd 2>/dev/null
mv $FREETZ_SSL_HOME_PATH30/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh.orig $FREETZ_SSL_HOME_PATH30/make/mod/files/root/usr/lib/mww/cgi/menu-new.sh 2>/dev/null
