#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/rrdtool/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/rrdtool/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/rrdtool/Config.in 2>/dev/null
