#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/openssl/Config.in.libs 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/openssl/Config.in.libs.orig $FREETZ_SSL_HOME_PATH/make/pkgs/openssl/Config.in.libs 2>/dev/null
