#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/avahi.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/patches/110-nls_cleanups.patch
mv $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/avahi.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/avahi.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/patches/110-nls_cleanups.patch.orig $FREETZ_SSL_HOME_PATH/make/pkgs/avahi/patches/110-nls_cleanups.patch 2>/dev/null
