#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/tiff.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/external.in.libs 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/tiff.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/tiff.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/external.in.libs.orig $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/external.in.libs 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/tiff/Config.in 2>/dev/null
