#!/bin/bash
rm -rf $FREETZ_SSL_HOME_PATH/make/pkgs/mod/files/root/etc/default.mod/mod.cfg 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/mod/files/root/etc/default.mod/mod.cfg.orig $FREETZ_SSL_HOME_PATH/make/pkgs/mod/files/root/etc/default.mod/mod.cfg 2>/dev/null
