#!/bin/bash
BAD_FB_EXT3_OS="$(grep '^FREETZ_TYPE_PREFIX_SERIES_SUBDIR=' .config | awk -F'"' '{print $2}' | xargs)"
BAD_FB_EXT3_TYP="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)"

if [ $BAD_FB_EXT3_OS = $BAD_EXT3_OS_75 ]
	then
		if [ $BAD_FB_EXT3_TYP = $BAD_EXT3_TYP ]
			then
		sed -i "s+# FREETZ_UDEVMOUNT_EXT3 is not set+FREETZ_UDEVMOUNT_EXT3=y+g" $FREETZ_SSL_HOME_PATH/.config
		sed -i "s+# FREETZ_MODULE_ext3 is not set+FREETZ_MODULE_ext3=y+g" $FREETZ_SSL_HOME_PATH/.config
	fi
fi

if [ $BAD_FB_EXT3_OS = $BAD_EXT3_OS_78 ]
	then
		if [ $BAD_FB_EXT3_TYP = $BAD_EXT3_TYP ]
			then
		sed -i "s+# FREETZ_UDEVMOUNT_EXT3 is not set+FREETZ_UDEVMOUNT_EXT3=y+g" $FREETZ_SSL_HOME_PATH/.config
		sed -i "s+# FREETZ_MODULE_ext3 is not set+FREETZ_MODULE_ext3=y+g" $FREETZ_SSL_HOME_PATH/.config
	fi
fi

if [ $BAD_FB_EXT3_OS = $BAD_EXT3_OS_80 ]
	then
		if [ $BAD_FB_EXT3_TYP = $BAD_EXT3_TYP ]
			then
		sed -i "s+# FREETZ_UDEVMOUNT_EXT3 is not set+FREETZ_UDEVMOUNT_EXT3=y+g" $FREETZ_SSL_HOME_PATH/.config
		sed -i "s+# FREETZ_MODULE_ext3 is not set+FREETZ_MODULE_ext3=y+g" $FREETZ_SSL_HOME_PATH/.config
	fi
fi
