#!/bin/bash
#### A ####
# ACME.sh (letsencrypt) https://freetz-ng.github.io/freetz-ng/make/acme.html
#source $PKGS_PATH_ON_OFF/acme_off
# Apache HTTP Server https://freetz-ng.github.io/freetz-ng/make/apache2.html
#source $PKGS_PATH_ON_OFF/apache2_off
# atop The program atop is an interactive monitor to view the load on a Linux system. It shows the occupation of the most critical hardware resources (from a performance point of view) on system level, i.e. cpu, memory, disk and network.
#source $PKGS_PATH_ON_OFF/atop_off
# AutoFS https://freetz-ng.github.io/freetz-ng/make/autofs.html
source $PKGS_PATH_ON_OFF/autofs_off

#### C ####
# Callmonitor https://freetz-ng.github.io/freetz-ng/make/callmonitor.html
#source $PKGS_PATH_ON_OFF/callmonitor_off
# Cifsmount https://freetz-ng.github.io/freetz-ng/make/cifsmount.html
#source $PKGS_PATH_ON_OFF/cifsmount_off

#### I ####
# ImageMagick (binary only)
#source $PKGS_PATH_ON_OFF/imagemagick_off

#### O ####
# OpenVPN https://freetz-ng.github.io/freetz-ng/make/openvpn.html
#source $PKGS_PATH_ON_OFF/openvpn_off

#### R ####
# RRDstats for RRDtool https://freetz-ng.github.io/freetz-ng/make/rrdstats.html
#source $PKGS_PATH_ON_OFF/rrdstats_off
# Cabelmodem Supplement to RRDstats for RRDtool
#source $PKGS_PATH_ON_OFF/rrdstatsc_off
# DigiTemp Supplement to RRDstats for RRDtool
#source $PKGS_PATH_ON_OFF/rrdstatsd_off


#### T ####
# Tor The Onion Router Anonymous Internet communication system. https://freetz-ng.github.io/freetz-ng/make/tor.html
#source $PKGS_PATH_ON_OFF/tor_off
