#!/bin/bash
if [[ $(lsb_release -rs) == "20.04" ]] || [[ $(lsb_release -rs) == "21.10" ]] || [[ $(lsb_release -rs) == "22.04" ]] || [[ $(lsb_release -rs) == "23.04" ]] || [[ $(lsb_release -rs) == "10" ]] || [[ $(lsb_release -rs) == "11" ]]; then # replace 20.04 by the number of release you want

PACKAGES="  autoconf automake autopoint bc binutils bison bsdmainutils bzip2 ccache cmake cpio curl ecj flex g++ gawk gcc gcc-multilib"
PACKAGES+=" gettext git graphicsmagick imagemagick inkscape intltool java-wrappers kmod lib32ncurses-dev lib32stdc++6 lib32z1-dev libacl1-dev"
PACKAGES+=" libcap-dev libelf-dev libglib2.0-dev libgnutls28-dev libncurses5-dev libreadline-dev libsqlite3-dev libssl-dev libstring-crc32-perl libtool-bin libusb-dev libxml2-dev libzstd-dev make ncftp"
PACKAGES+=" netcat-openbsd net-tools patch patchutils perl pkg-config pv rsync sharutils sqlite3 subversion sudo texinfo tofrodos unar unzip uuid-dev wget zip zlib1g-dev"
#PACKAGES+=" device-tree-compiler" # for FIT-Image
PACKAGES+=" libc6-dev-i386"
	
if ! dpkg -s $PACKAGES >/dev/null 2>&1; then
	printf "${YELLOW}Installing prerequisite packages...\n${NC}"
#	sudo dpkg --add-architecture i386
#	sudo add-apt-repository ppa:git-core/ppa
	sudo apt-get install $PACKAGES
	cd /tmp
	wget http://mirrors.kernel.org/ubuntu/pool/universe/u/upx-ucl/upx-ucl_3.95-2build1_amd64.deb
	sudo apt install /tmp/upx-ucl_3.95-2build1_amd64.deb
	echo upx-ucl hold | sudo dpkg --set-selections
	sudo apt-get update && sudo apt-get -y upgrade && sudo apt dist-upgrade && sudo apt autoclean && sudo apt autoremove
fi
else
       echo "Non-compatible version"
       echo "read here https://freetz-ng.github.io/freetz-ng/PREREQUISITES"
       exit
fi
