#!/bin/bash
DOWNGRADE_FOR="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)" 2>/dev/null
if [ $DOWNGRADE_FOR = $LIBUSB1_7530AX ]
	then
		echo -e ${GREEN}"Freetz files downgrade for libusb1."${NC}
		cp -ar $I_MATIK_PATH/support/freetz/scripts/patches/downgrade/make/libs/libusb1.patch "$FREETZ_SSL_HOME_PATH/" 2>/dev/null
		patch -p0 -b < libusb1.patch
		rm -rf "$FREETZ_SSL_HOME_PATH/libusb1.patch" 2>/dev/null
fi
