#!/bin/bash
DOWNGRADE_FOR_7530AX="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)" 2>/dev/null
DOWNGRADE_FOR_PATCHELF="$(grep '^FREETZ_TARGET_ARCH_ENDIANNESS_DEPENDENT=' .config | awk -F'"' '{print $2}' | xargs)" 2>/dev/null

if [ $DOWNGRADE_FOR_7530AX = $LIBUSB1_7530AX ]
	then
		source $I_MATIK_PATH/support/freetz/scripts/patches/downgrade/libusb1_off/libusb1
fi	
