#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/db/db.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/db/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/db/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/db/patches/100-no_docs.db.patchs 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/db/db.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/db/db.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/db/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/db/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/db/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/db/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/db/patches/020-drop_backtrace_dependency.db.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/db/patches/020-drop_backtrace_dependency.db.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/db/patches/100-no_docs.db.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/db/patches/100-no_docs.db.patch 2>/dev/null
