#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libgsm/libgsm.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/010-shared_lib.libgsm.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/030-missing_includes.libgsm.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/102-cplusplus.debian.libgsm.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/105-compiler_warnings.debian.libgsm.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libgsm/libgsm.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libgsm/libgsm.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/010-shared_lib.libgsm.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/010-shared_lib.libgsm.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/030-missing_includes.libgsm.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/030-missing_includes.libgsm.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/102-cplusplus.debian.libgsm.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/102-cplusplus.debian.libgsm.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/105-compiler_warnings.debian.libgsm.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libgsm/patches/105-compiler_warnings.debian.libgsm.patch 2>/dev/null
