#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libnet/libnet.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libnet/libnet.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libnet/libnet.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libnet/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libnet/patches/100-cross-compilation.libnet.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libnet/patches/100-cross-compilation.libnet.patch 2>/dev/null
