#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/liboping/liboping.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/100-no-Werror.liboping.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/liboping.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/liboping.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/100-no-Werror.liboping.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/100-no-Werror.liboping.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/110-IPv6_defines.liboping.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/110-IPv6_defines.liboping.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/120-IPv6_structs.liboping.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/liboping/patches/120-IPv6_structs.liboping.patch 2>/dev/null
