#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/openobex/openobex.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/openobex/patches/100-makefile_no_usb.openobex.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/openobex/openobex.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/openobex/openobex.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/openobex/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/openobex/patches/100-makefile_no_usb.openobex.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/openobex/patches/100-makefile_no_usb.openobex.patch 2>/dev/null
