#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/protobuf-c/protobuf-c.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/protobuf-c/protobuf-c.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/protobuf-c/protobuf-c.mk 2>/dev/null
