#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/speex/speex.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/speex/Makefile.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/speex/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/speex/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/speex/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/speex.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/speex.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/Makefile.in.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/Makefile.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/Config.in.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/speex/patches.orig $FREETZ_SSL_HOME_PATH/make/libs/speex/patches 2>/dev/null
