#!/bin/bash
if [ ! -f $FREETZ_SSL_HOME_PATH/make/pkgs/mod/files/root/usr/mww/cgi-bin/status.d/10-box.sh.orig ]; then
	sleep 0
else
	source $PATCH_OFF 2>/dev/null
	source $PRIVAT_PATCH_OFF 2>/dev/null
	grep -v oscam $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
	source $I_MATIK_PATH/support/freetz/scripts/pkgs_on_off/skins_off 2>/dev/null
	sed -i "s+${VERSIONS_NR}+xxxxx+g" $VERSION
fi	

if [ ! -f $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk.orig ]; then
	sleep 0
else
	rm -f $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk 2>/dev/null
	mv $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk 2>/dev/null
fi

#if [ ! -f $PRIVAT_INHAUS/inhaus_on ]; then
#	sleep 0
#else
#	mv $PRIVAT_INHAUS/inhaus_on $PRIVAT_INHAUS/inhaus_on1
#	mv $PRIVAT_INHAUS/inhaus_off $PRIVAT_INHAUS/inhaus_off1
#fi
