#!/bin/bash
if [ ! -f $FREETZ_SSL_HOME_PATH/make/pkgs/mod/files/root/usr/mww/cgi-bin/status.d/10-box.sh.orig ]; then
	sleep 0
else
	source $PATCH_OFF 2>/dev/null
	source $PRIVAT_PATCH_OFF 2>/dev/null
	grep -v oscam $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
	source $I_MATIK_PATH/support/freetz/scripts/pkgs_on_off/skins_off 2>/dev/null
	sed -i "s+${VERSIONS_NR}+xxxxx+g" $VERSION
fi	

if [ ! -f $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk.orig ]; then
	sleep 0
else
	rm -f $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk 2>/dev/null
	mv $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libusb1/libusb1.mk 2>/dev/null
fi

if [ ! -f $I_MATIK_PATH/support/s3_releases/scripts/oscam_mit ]; then
	sleep 0
else
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam $I_MATIK_PATH/support/s3_releases/scripts/oscam_ohne
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_mit $I_MATIK_PATH/support/s3_releases/scripts/oscam
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu_ohne
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu_mit $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam_ohne
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam_mit $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod_ohne
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod_mit $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc_ohne
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc_mit $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc	
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc.profile $OSCAM_PATH/profiles/webif-libusb-pcsc.profile_ohne
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc.profile_mit $OSCAM_PATH/profiles/webif-libusb-pcsc.profile
	
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile_ohne
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile_mit $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile
	
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile_ohne
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile_mit $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile_ohne
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile_mit $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile_ohne
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile_mit $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile_ohne
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile_mit $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc-emu.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc-emu.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc-emu.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-dvbapi-libusb-pcsc-emu.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-emu.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-emu.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-emu.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-emu.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6.profile
	
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6-emu.profile $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6-emu.profile_ohne
	mv $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6-emu.profile_mit $MY_FILES_HOME_PATH_OSCAM/support/profiles/webif-libusb-pcsc-ipv6-emu.profile
fi

#if [ ! -f $PRIVAT_INHAUS/inhaus_on ]; then
#	sleep 0
#else
#	mv $PRIVAT_INHAUS/inhaus_on $PRIVAT_INHAUS/inhaus_on1
#	mv $PRIVAT_INHAUS/inhaus_off $PRIVAT_INHAUS/inhaus_off1
#fi
