#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libcap/libcap.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libcap/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libcap/libcap.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libcap/libcap.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libcap/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libcap/external.files 2>/dev/null
