#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libmnl/libmnl.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libmnl/libmnl.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libmnl/libmnl.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libmnl/external.files 2>/dev/null
