#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libonig/libonig.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libonig/patches/100-only_src.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libonig/libonig.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libonig/libonig.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libonig/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libonig/patches/100-only_src.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libonig/patches/100-only_src.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libonig/patches/102-no_include_dir.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libonig/patches/102-no_include_dir.patch 2>/dev/null
