#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/libtasn1.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/patches/100-build_lib_only.libtasn1.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/libtasn1.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/libtasn1.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/patches/100-build_lib_only.libtasn1.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libtasn1/patches/100-build_lib_only.libtasn1.patch 2>/dev/null
