#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libxml2/libxml2.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/100-no_docs_examples_tests.libxml2.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/110-pthread_fixes.libxml2.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libxml2/libxml2.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/libxml2/libxml2.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/libxml2/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/100-no_docs_examples_tests.libxml2.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/100-no_docs_examples_tests.libxml2.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/110-pthread_fixes.libxml2.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/libxml2/patches/110-pthread_fixes.libxml2.patch 2>/dev/null
