#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/srtp.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/010-AR.srtp.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/020-install.srtp.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/040-shared_lib.srtp.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/srtp.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/srtp.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/010-AR.srtp.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/010-AR.srtp.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/020-install.srtp.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/020-install.srtp.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/040-shared_lib.srtp.patch.orig $FREETZ_SSL_HOME_PATH/make/libs/srtp/patches/040-shared_lib.srtp.patch 2>/dev/null
