#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/libs/yaml/yaml.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/yaml/yaml.mk.orig $FREETZ_SSL_HOME_PATH/make/libs/yaml/yaml.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.in.orig $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.files.orig $FREETZ_SSL_HOME_PATH/make/libs/yaml/external.files 2>/dev/null
