#!/bin/bash
if [[ ! -e $I_MATIK_PATH_OSCAM ]]; then
umask 0022
    git clone https://github.com/gorgone/s3_releases $I_MATIK_PATH_OSCAM
cp -ar /$MY_FILES_HOME_PATH_OSCAM/* $I_MATIK_PATH_OSCAM/
#elif [[ ! -d $I_MATIK_PATH_OSCAM ]]; then
#    echo "$I_MATIK_PATH_OSCAM existiert bereits, ist aber kein Verzeichnis" 1>&2
fi

if [[ ! -e $I_MATIK_PATH_OSCAM/oscam-svn ]]; then
    svn checkout https://svn.streamboard.tv/oscam/trunk $I_MATIK_PATH_OSCAM/oscam-svn
#elif [[ ! -d $I_MATIK_PATH_OSCAM/oscam-svn ]]; then
#    echo "$I_MATIK_PATH_OSCAM/oscam-svn existiert bereits, ist aber kein Verzeichnis" 1>&2
fi

if [[ ! -e $I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm ]]; then
$I_MATIK_PATH_OSCAM/./s3 tcrepair fritz74xxOS65_arm
rm -rf $I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm
#elif [[ ! -d $I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm ]]; then
#    echo "$I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm existiert bereits, ist aber kein Verzeichnis " 1>&2
fi

cd $I_MATIK_PATH_OSCAM/oscam-svn && OSCAMVERSION_ALT="$(./config.sh -r)"
cd $I_MATIK_PATH_OSCAM/oscam-svn && svn up && OSCAMVERSION_NEU="$(./config.sh -r)"

if [[ ! -e $FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$BOX_NAME/oscam-svn$OSCAMVERSION_NEU-fritz${BOX_NAME}_${FUD_COMMENT_SSL}_arm_freetz-$I_MATIK_OSCAM_reader.upx ]]; then
find "$FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$BOX_NAME/" -name "oscam-svn$OSCAMVERSION_ALT-fritz${BOX_NAME}_${FUD_COMMENT_SSL}_arm_freetz-$I_MATIK_OSCAM_reader.upx" -type f -mmin +0 -delete 
rm -rf $I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm
ln -s $FREETZ_SSL_HOME_PATH/toolchain/target $I_MATIK_PATH_OSCAM/support/toolchains/fritz74xxOS65_arm

$I_MATIK_PATH_OSCAM/./s3 fritz74xxOS65_arm -p=$I_MATIK_OSCAM_reader.profile
mv $I_MATIK_PATH_OSCAM/support/binaries/oscam-svn$OSCAMVERSION_NEU-fritz74xxOS65_arm-$I_MATIK_OSCAM_reader-upx $FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$BOX_NAME/oscam-svn$OSCAMVERSION_NEU-fritz${BOX_NAME}_${FUD_COMMENT_SSL}_arm_freetz-$I_MATIK_OSCAM_reader.upx
elif [[ ! -d $FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$BOX_NAME/oscam-svn$OSCAMVERSION_NEU-fritz${BOX_NAME}_${FUD_COMMENT_SSL}_arm_freetz-$I_MATIK_OSCAM_reader.upx ]]; then
    echo "$FREETZ_IMAGE_PATH/$END_IMAGE_PATH/$BOX_NAME/oscam-svn$OSCAMVERSION_NEU-fritz${BOX_NAME}_${FUD_COMMENT_SSL}_arm_freetz-$I_MATIK_OSCAM_reader.upx already exists" 1>&2
fi
