#!/bin/bash

check_and_download_oscam() {
	if [ -d "${OSCAM_ADDON_PATH}" ]; then
		return 0
	fi

	echo -e "${YELLOW}Unfortunately the ${OSCAM_ADDON_PATH} is not available, so an automatic download is now started.${NC}"
	grep -v "${OSCAM_ADDON_VERSION}" "$FREETZ_SSL_HOME_PATH/addon/static.pkg" > "$FREETZ_SSL_HOME_PATH/addon/tempdatei"
	mv "$FREETZ_SSL_HOME_PATH/addon/tempdatei" "$FREETZ_SSL_HOME_PATH/addon/static.pkg"

	cd "$MY_FILES_HOME_PATH/addon" || exit
	wget "https://freetz.digital-eliteboard.com/Teamserver/Freetz/Addon/oscam%20${OSCAM_ADDON_VERSION:6:4}x/${OSCAM_ADDON_VERSION:6:5}/${OSCAM_ADDON_VERSION}.tar.gz" 2>/dev/null
	tar xfvz "${OSCAM_ADDON_VERSION}.tar.gz"
	chmod -R 755 "${OSCAM_ADDON_VERSION}"
	rm -rf "${OSCAM_ADDON_VERSION_OLD}"
	rm "${OSCAM_ADDON_VERSION}.tar.gz"

	echo -e "${RED}Please start again, because the oscam Add-on is not under Add-on.${NC}"
	source "$PATCH_OFF"
	source "$FRIENDS_UPDATE_ADDON_OFF" 2>/dev/null
	rm -f "$FREETZ_SSL_HOME_PATH/.config"
	exit
}

if [ -n "$PARAM_OSCAM" ]; then
	check_and_download_oscam
	source "$OSCAM_ON"
	sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
fi

if [ -n "$PARAM_OSCAM_EMU" ]; then
	check_and_download_oscam
	source "$OSCAM_ON"
	sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
fi

if [ -n "$PARAM_OSCAM_SMOD" ]; then
	check_and_download_oscam
	source "$OSCAM_ON"
	sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
fi

if [ -n "$PARAM_OSCAM_NCAM" ]; then
	check_and_download_oscam
	source "$OSCAM_ON"
	sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
fi

if [ -n "$PARAM_OSCAM_TOOL" ]; then
	check_and_download_oscam
	source "$OSCAM_ON"
	sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
fi
