#!/bin/bash
	if [ -z $PARAM_OSCAM ]; then
		sleep 0
	else

	if [ -d "${OSCAM_ADDON_PATH}" ];then 
		sleep 0
	else 
		echo -e ${YELLOW}"Unfortunately the ${OSCAM_ADDON_PATH} is not available, so an automatic download is now started."${NC}
		grep -v ${NEW_OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		cd ${FREETZ_SSL_HOME_PATH}/addon
		wget https://www.freetz.digital-eliteboard.com/Teamserver/Freetz/Addon/oscam%20${OSCAM_ADDON_VERSION:6:4}x/${OSCAM_ADDON_VERSION:6:5}/${OSCAM_ADDON_VERSION}.tar.gz 2>/dev/null
		tar xfvz ${OSCAM_ADDON_VERSION}.tar.gz
		chmod -v 755 ${OSCAM_ADDON_VERSION}
		rm ${OSCAM_ADDON_VERSION}.tar.gz
		echo -e ${GREEN}"rolu2 from the DEB forum is responsible for maintaining the oscam add-on. I have only developed one way that it is equally available to everyone in i-matik. Therefore, I will not give support for the Oscam add-on."${NC}
		echo -e ${RED}"Please start again, because the oscam Add-on of rolu2 from the DEB Forum was not under Add-on."${NC}
		source $PATCH_OFF
		rm -f $FREETZ_SSL_HOME_PATH/.config
		exit
	fi
		source $OSCAM_ON
		sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	fi
	
	if [ -z $PARAM_OSCAM_EMU ]; then
		sleep 0
	else

	if [ -d "${OSCAM_ADDON_PATH}" ];then 
		sleep 0
	else 
		echo -e ${YELLOW}"Unfortunately the ${OSCAM_ADDON_PATH} is not available, so an automatic download is now started."${NC}
		grep -v ${NEW_OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		cd ${FREETZ_SSL_HOME_PATH}/addon
		wget https://www.freetz.digital-eliteboard.com/Teamserver/Freetz/Addon/oscam%20${OSCAM_ADDON_VERSION:6:4}x/${OSCAM_ADDON_VERSION:6:5}/${OSCAM_ADDON_VERSION}.tar.gz 2>/dev/null
		tar xfvz ${OSCAM_ADDON_VERSION}.tar.gz
		chmod -v 755 ${OSCAM_ADDON_VERSION}
		rm ${OSCAM_ADDON_VERSION}.tar.gz
		echo -e ${GREEN}"rolu2 from the DEB forum is responsible for maintaining the oscam add-on. I have only developed one way that it is equally available to everyone in i-matik. Therefore, I will not give support for the Oscam add-on."${NC}
		echo -e ${RED}"Please start again, because the oscam Add-on of rolu2 from the DEB Forum was not under Add-on."${NC}
		source $PATCH_OFF
		rm -f $FREETZ_SSL_HOME_PATH/.config
		exit
	fi
		source $OSCAM_ON
		sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	fi
	
	if [ -z $PARAM_OSCAM_SMOD ]; then
		sleep 0
	else

	if [ -d "${OSCAM_ADDON_PATH}" ];then 
		sleep 0
	else 
		echo -e ${YELLOW}"Unfortunately the ${OSCAM_ADDON_PATH} is not available, so an automatic download is now started."${NC}
		grep -v ${NEW_OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		cd ${FREETZ_SSL_HOME_PATH}/addon
		wget https://www.freetz.digital-eliteboard.com/Teamserver/Freetz/Addon/oscam%20${OSCAM_ADDON_VERSION:6:4}x/${OSCAM_ADDON_VERSION:6:5}/${OSCAM_ADDON_VERSION}.tar.gz 2>/dev/null
		tar xfvz ${OSCAM_ADDON_VERSION}.tar.gz
		chmod -v 755 ${OSCAM_ADDON_VERSION}
		rm ${OSCAM_ADDON_VERSION}.tar.gz
		echo -e ${GREEN}"rolu2 from the DEB forum is responsible for maintaining the oscam add-on. I have only developed one way that it is equally available to everyone in i-matik. Therefore, I will not give support for the Oscam add-on."${NC}
		echo -e ${RED}"Please start again, because the oscam Add-on of rolu2 from the DEB Forum was not under Add-on."${NC}
		source $PATCH_OFF
		rm -f $FREETZ_SSL_HOME_PATH/.config
		exit
	fi
		source $OSCAM_ON
		sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	fi
	
	if [ -z $PARAM_OSCAM_TOOL ]; then
		sleep 0
	else

	if [ -d "${OSCAM_ADDON_PATH}" ];then 
		sleep 0
	else 
		echo -e ${YELLOW}"Unfortunately the ${OSCAM_ADDON_PATH} is not available, so an automatic download is now started."${NC}
		grep -v ${NEW_OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		cd ${FREETZ_SSL_HOME_PATH}/addon
		wget https://www.freetz.digital-eliteboard.com/Teamserver/Freetz/Addon/oscam%20${OSCAM_ADDON_VERSION:6:4}x/${OSCAM_ADDON_VERSION:6:5}/${OSCAM_ADDON_VERSION}.tar.gz 2>/dev/null
		tar xfvz ${OSCAM_ADDON_VERSION}.tar.gz
		chmod -v 755 ${OSCAM_ADDON_VERSION}
		rm ${OSCAM_ADDON_VERSION}.tar.gz
		echo -e ${GREEN}"rolu2 from the DEB forum is responsible for maintaining the oscam add-on. I have only developed one way that it is equally available to everyone in i-matik. Therefore, I will not give support for the Oscam add-on."${NC}
		echo -e ${RED}"Please start again, because the oscam Add-on of rolu2 from the DEB Forum was not under Add-on."${NC}
		source $PATCH_OFF
		rm -f $FREETZ_SSL_HOME_PATH/.config
		exit
	fi
		source $OSCAM_ON
		sed -i "s+FREETZ_TOOLCHAIN_CCACHE=y+# FREETZ_TOOLCHAIN_CCACHE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	fi
