#!/bin/bash
BAD_FB_WD_OS="$(grep '^FREETZ_TYPE_PREFIX_SERIES_SUBDIR=' .config | awk -F'"' '{print $2}' | xargs)"
BAD_FB_WD_TYP="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)"
if [ $BAD_FB_WD_OS = $BAD_WD_OS ]
	then
		if [ $BAD_FB_WD_TYP = $WATCHDOG_CLEAN1 ]
			then
				source $WATCHDOG_ON
		elif [ $BAD_FB_WD_TYP = $WATCHDOG_CLEAN2 ]
			then
				source $WATCHDOG_ON
		elif [ $BAD_FB_TYP = $WATCHDOG_CLEAN3 ]
			then
				source $WATCHDOG_ON
		elif [ $BAD_FB_TYP = $WATCHDOG_CLEAN4 ]
			then
				source $WATCHDOG_ON
		fi
fi
