#!/bin/bash
# Update .config using a single sed command
sed -i -e "s+# FREETZ_USER_LEVEL_EXPERT is not set+FREETZ_USER_LEVEL_EXPERT=y+g" \
	-e "s+FREETZ_USER_LEVEL_DEVELOPER=y+# FREETZ_USER_LEVEL_DEVELOPER is not set+g" \
	"$FREETZ_SSL_HOME_PATH/.config"
