#!/bin/bash
# Get necessary values from .config
BAD_FB_WD_OS="$(grep '^FREETZ_TYPE_PREFIX_SERIES_SUBDIR=' .config | awk -F'"' '{print $2}' | xargs)"
BAD_FB_WD_TYP="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)"

# Check conditions and source WATCHDOG_ON if any condition matches
if [ "$BAD_FB_WD_OS" = "$BAD_WD_OS" ]; then
	case "$BAD_FB_WD_TYP" in
		"$WATCHDOG_CLEAN1" | "$WATCHDOG_CLEAN2" | "$WATCHDOG_CLEAN3" | "$WATCHDOG_CLEAN4")
		source "$WATCHDOG_ON"
		;;
	esac
fi
