#!/bin/bash
# Extract the bad FB watchdog OS and type
BAD_FB_WD_OS="$(grep '^FREETZ_TYPE_PREFIX_SERIES_SUBDIR=' .config | awk -F'"' '{print $2}' | xargs)"
BAD_FB_WD_TYP="$(grep '^FREETZ_TYPE_PREFIX=' .config | awk -F'"' '{print $2}' | xargs)"

# Check if the bad FB watchdog OS matches
if [[ "$BAD_FB_WD_OS" == "$BAD_WD_OS" ]]; then
	# Check if the bad FB watchdog type matches any of the WATCHDOG_CLEAN values
	if [[ "$BAD_FB_WD_TYP" == "$WATCHDOG_CLEAN1" || 
		"$BAD_FB_WD_TYP" == "$WATCHDOG_CLEAN2" || 
		"$BAD_FB_WD_TYP" == "$WATCHDOG_CLEAN3" || 
		"$BAD_FB_WD_TYP" == "$WATCHDOG_CLEAN4" ]]; then
		source "$WATCHDOG_OFF"
	fi
fi
