#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/toolchain/make/target/binutils/binutils.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/toolchain/make/target/binutils/binutils.mk.orig $FREETZ_SSL_HOME_PATH/toolchain/make/target/binutils/binutils.mk 2>/dev/null
