#!/bin/bash

# Disable specific packages and libraries
sed -i "s+FREETZ_PACKAGE_ATOP=y+# FREETZ_PACKAGE_ATOP is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_LIB_libz=y+# FREETZ_LIB_libz is not set+g" "$FREETZ_SSL_HOME_PATH/.config"

# Remove specific libraries from the config file
for LIB in FREETZ_LIB_libncurses FREETZ_LIB_libform FREETZ_LIB_libmenu FREETZ_LIB_libpanel; do
	grep -v "$LIB" "$FREETZ_SSL_HOME_PATH/.config" > "$FREETZ_SSL_HOME_PATH/tempdatei"
	mv "$FREETZ_SSL_HOME_PATH/tempdatei" "$FREETZ_SSL_HOME_PATH/.config"
done
