#!/bin/bash

# Disable various Freetz packages and libraries in the configuration file
sed -i -e "s+FREETZ_PACKAGE_IMAGEMAGICK=y+# FREETZ_PACKAGE_IMAGEMAGICK is not set+g" \
	-e "s+FREETZ_PACKAGE_GHOSTSCRIPT_FONTS=y+# FREETZ_PACKAGE_GHOSTSCRIPT_FONTS is not set+g" \
	-e "s+FREETZ_LIB_libfreetype=y+# FREETZ_LIB_libfreetype is not set+g" \
	-e "s+FREETZ_LIB_libjpeg=y+# FREETZ_LIB_libjpeg is not set+g" \
	-e "s+FREETZ_LIB_libxml2=y+# FREETZ_LIB_libxml2 is not set+g" \
	"$FREETZ_SSL_HOME_PATH/.config"
