#!/bin/bash

# Disable OpenVPN and related libraries/modules in the configuration
sed -i "s+FREETZ_PACKAGE_OPENVPN=y+# FREETZ_PACKAGE_OPENVPN is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_LIB_liblzo2=y+# FREETZ_LIB_liblzo2 is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_MODULE_tun=y+# FREETZ_MODULE_tun is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_REMOVE_AVM_VPN=y+# FREETZ_REMOVE_AVM_VPN is not set+g" "$FREETZ_SSL_HOME_PATH/.config"

# Array of configuration options to remove
options_to_remove=(
	"FREETZ_PACKAGE_OPENVPN_VERSION_"
	"FREETZ_PACKAGE_OPENVPN_USE_V0_CGI"
	"FREETZ_PACKAGE_OPENVPN_USE_V1_CGI"
	"FREETZ_PACKAGE_OPENVPN_USE_V2_CGI"
	"FREETZ_PACKAGE_OPENVPN_OPENSSL"
	"FREETZ_PACKAGE_OPENVPN_MBEDTLS"
	"FREETZ_PACKAGE_OPENVPN_WITH_BLOWFISH"
	"FREETZ_PACKAGE_OPENVPN_STATIC"
	"FREETZ_PACKAGE_OPENVPN_WITH_LZO"
	"FREETZ_PACKAGE_OPENVPN_WITH_LZ4"
	"FREETZ_PACKAGE_OPENVPN_WITH_TRAFFIC_OBFUSCATION"
	"FREETZ_PACKAGE_OPENVPN_WITH_MGMNT"
	"FREETZ_PACKAGE_OPENVPN_ENABLE_SMALL"
	"FREETZ_PACKAGE_OPENVPN_USE_IPROUTE"
	"FREETZ_MODULE_yf_patchkernel"
	"FREETZ_PACKAGE_OPENVPN_CGI"
	"FREETZ_BUSYBOX_FEATURE_PS_WIDE"
	"FREETZ_LIB_libcap_ng"
	"FREETZ_LIB_liblz4"
)

# Remove each specified option from the configuration
for option in "${options_to_remove[@]}"; do
	grep -v "$option" "$FREETZ_SSL_HOME_PATH/.config" > "$FREETZ_SSL_HOME_PATH/tempdatei" && mv "$FREETZ_SSL_HOME_PATH/tempdatei" "$FREETZ_SSL_HOME_PATH/.config"
done

# Uncomment if needed for further configuration changes
# sed -i "s+FREETZ_PACKAGE_IPTABLES=y+# FREETZ_PACKAGE_IPTABLES is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
# sed -i "s+# FREETZ_USER_LEVEL_EXPERT is not set+FREETZ_USER_LEVEL_EXPERT=y+g" "$FREETZ_SSL_HOME_PATH/.config"
# sed -i "s+FREETZ_USER_LEVEL_DEVELOPER=y+# FREETZ_USER_LEVEL_DEVELOPER is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
