#!/bin/bash
sed -i "s+# FREETZ_PACKAGE_OSCAM is not set+FREETZ_PACKAGE_OSCAM=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_CCID is not set+FREETZ_PACKAGE_CCID=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_PCSC_LITE is not set+FREETZ_PACKAGE_PCSC_LITE=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_LIB_libpcsclite is not set+FREETZ_LIB_libpcsclite=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_LIB_libusb_0 is not set+FREETZ_LIB_libusb_0=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_LIB_libusb_1 is not set+FREETZ_LIB_libusb_1=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_LIB_libftdi is not set+FREETZ_LIB_libftdi=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_USBIDS is not set+FREETZ_PACKAGE_USBIDS=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_USBUTILS is not set+FREETZ_PACKAGE_USBUTILS=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_MODULE_ftdi_sio is not set+FREETZ_MODULE_ftdi_sio=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_MODULE_pl2303 is not set+FREETZ_MODULE_pl2303=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_MODULE_usbserial is not set+FREETZ_MODULE_usbserial=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PATCH_UDEVMOUNT is not set+FREETZ_PATCH_UDEVMOUNT=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PATCH_MAXDEVCOUNT is not set+FREETZ_PATCH_MAXDEVCOUNT=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_CUSTOM_UDEV_RULES is not set+FREETZ_CUSTOM_UDEV_RULES=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+FREETZ_DROP_NOEXEC_EXTERNAL=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PATCH_FREETZMOUNT is not set+FREETZ_PATCH_FREETZMOUNT=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_AVM_PORTFW is not set+FREETZ_PACKAGE_AVM_PORTFW=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_AVM_FIREWALL is not set+FREETZ_PACKAGE_AVM_FIREWALL=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_AVM_FORWARDING is not set+FREETZ_PACKAGE_AVM_FORWARDING=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_PACKAGE_STRACE is not set+FREETZ_PACKAGE_STRACE=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_REPLACE_KERNEL is not set+FREETZ_REPLACE_KERNEL=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+# FREETZ_LIB_libssl is not set+FREETZ_LIB_libssl=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+$MASTERBOX_NEU+with_readerdriver_$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+$CLIENTBOX_NEU+with_readerdriver_$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+$WUNSCHIMAGE_NEU+with_readerdriver_$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+openssl_multi_masterbox+with_readerdriver_openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
sed -i "s+openssl_multi_clientbox+with_readerdriver_openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null

PUMA7_IMAGE="puma7"
PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
then
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam $I_MATIK_PATH/support/s3_releases/scripts/oscam_mit
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_ohne $I_MATIK_PATH/support/s3_releases/scripts/oscam
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu_mit
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu_ohne $I_MATIK_PATH/support/s3_releases/scripts/oscam_emu
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam_mit
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam_ohne $I_MATIK_PATH/support/s3_releases/scripts/oscam_ncam
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod_mit
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod_ohne $I_MATIK_PATH/support/s3_releases/scripts/oscam_smod
	
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc_mit
	mv $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc_ohne $I_MATIK_PATH/support/s3_releases/scripts/oscam_tc
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc.profile $OSCAM_PATH/profiles/webif-libusb-pcsc.profile_mit
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc.profile_ohne $OSCAM_PATH/profiles/webif-libusb-pcsc.profile
	
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile_mit
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile_ohne $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc.profile
	
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile_mit
	mv $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile_ohne $OSCAM_PATH/profiles/webif-dvbapi-libusb-pcsc-emu.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile_mit
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile_ohne $OSCAM_PATH/profiles/webif-libusb-pcsc-emu.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile_mit
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile_ohne $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6.profile
	
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile_mit
	mv $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile_ohne $OSCAM_PATH/profiles/webif-libusb-pcsc-ipv6-emu.profile
fi
