#!/bin/bash
if [ -z $PARAM_OSCAM ]; then
		sleep 0
	else
		sed -i "s+FREETZ_LIB_libgcrypt=y+# FREETZ_LIB_libgcrypt is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libntfs=y+# FREETZ_LIB_libntfs is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libfuse=y+# FREETZ_LIB_libfuse is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_0=y+# FREETZ_LIB_libusb_0 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libnettle=y+# FREETZ_LIB_libnettle is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libftdi=y+# FREETZ_LIB_libftdi is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX_LSUSB=y+# FREETZ_BUSYBOX_LSUSB is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS=y+# FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libcrypto=y+# FREETZ_LIB_libcrypto is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libgpg_error=y+# FREETZ_LIB_libgpg_error is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_OSCAM=y+# FREETZ_PACKAGE_OSCAM is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_CCID=y+# FREETZ_PACKAGE_CCID is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_PCSC_LITE=y+# FREETZ_PACKAGE_PCSC_LITE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libpcsclite=y+# FREETZ_LIB_libpcsclite is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_1=y+# FREETZ_LIB_libusb_1 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBIDS=y+# FREETZ_PACKAGE_USBIDS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBUTILS=y+# FREETZ_PACKAGE_USBUTILS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_ftdi_sio=y+# FREETZ_MODULE_ftdi_sio is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_pl2303=y+# FREETZ_MODULE_pl2303 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_usbserial=y+# FREETZ_MODULE_usbserial is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_UDEVMOUNT=y+# FREETZ_PATCH_UDEVMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_MAXDEVCOUNT=y+# FREETZ_PATCH_MAXDEVCOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_CUSTOM_UDEV_RULES=y+# FREETZ_CUSTOM_UDEV_RULES is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_DROP_NOEXEC_EXTERNAL=y+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_FREETZMOUNT=y+# FREETZ_PATCH_FREETZMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_PORTFW=y+# FREETZ_PACKAGE_AVM_PORTFW is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FIREWALL=y+# FREETZ_PACKAGE_AVM_FIREWALL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FORWARDING=y+# FREETZ_PACKAGE_AVM_FORWARDING is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_STRACE=y+# FREETZ_PACKAGE_STRACE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v ${OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		sed -i "s+with_readerdriver_$MASTERBOX_NEU+$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$CLIENTBOX_NEU+$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$WUNSCHIMAGE_NEU+$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi_masterbox+openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi-clientbox+openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS_PLUS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_REISER_FS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_PACKAGE_USBIDS_FORCE_DOWNLOAD $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		PUMA7_IMAGE="puma7"
		PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
		if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
		then
		sed -i "s+FREETZ_HOSTTOOLS_DOWNLOAD=y+# FREETZ_HOSTTOOLS_DOWNLOAD is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		fi
		##### test
		sed -i "s+FREETZ_PACKAGE_XZ=y+# FREETZ_PACKAGE_XZ is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_liblzma=y+# FREETZ_LIB_liblzma is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libz=y+# FREETZ_LIB_libz is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libelf=y+# FREETZ_LIB_libelf is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libltdl=y+# FREETZ_LIB_libltdl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX___V136_FEATURE_MD5_SHA1_SUM_CHECK=y+# FREETZ_BUSYBOX___V136_FEATURE_MD5_SHA1_SUM_CHECK is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
# Get custom image file name part from .config
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
#FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT)"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"
fi

if [ -z $PARAM_OSCAM_EMU ]; then
		sleep 0
	else
		sed -i "s+FREETZ_LIB_libgcrypt=y+# FREETZ_LIB_libgcrypt is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libntfs=y+# FREETZ_LIB_libntfs is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libfuse=y+# FREETZ_LIB_libfuse is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_0=y+# FREETZ_LIB_libusb_0 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libnettle=y+# FREETZ_LIB_libnettle is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libftdi=y+# FREETZ_LIB_libftdi is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX_LSUSB=y+# FREETZ_BUSYBOX_LSUSB is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS=y+# FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libcrypto=y+# FREETZ_LIB_libcrypto is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libgpg_error=y+# FREETZ_LIB_libgpg_error is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_OSCAM=y+# FREETZ_PACKAGE_OSCAM is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_CCID=y+# FREETZ_PACKAGE_CCID is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_PCSC_LITE=y+# FREETZ_PACKAGE_PCSC_LITE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libpcsclite=y+# FREETZ_LIB_libpcsclite is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_1=y+# FREETZ_LIB_libusb_1 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBIDS=y+# FREETZ_PACKAGE_USBIDS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBUTILS=y+# FREETZ_PACKAGE_USBUTILS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_ftdi_sio=y+# FREETZ_MODULE_ftdi_sio is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_pl2303=y+# FREETZ_MODULE_pl2303 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_usbserial=y+# FREETZ_MODULE_usbserial is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_UDEVMOUNT=y+# FREETZ_PATCH_UDEVMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_MAXDEVCOUNT=y+# FREETZ_PATCH_MAXDEVCOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_CUSTOM_UDEV_RULES=y+# FREETZ_CUSTOM_UDEV_RULES is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_DROP_NOEXEC_EXTERNAL=y+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_FREETZMOUNT=y+# FREETZ_PATCH_FREETZMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_PORTFW=y+# FREETZ_PACKAGE_AVM_PORTFW is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FIREWALL=y+# FREETZ_PACKAGE_AVM_FIREWALL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FORWARDING=y+# FREETZ_PACKAGE_AVM_FORWARDING is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_STRACE=y+# FREETZ_PACKAGE_STRACE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v ${OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		sed -i "s+with_readerdriver_$MASTERBOX_NEU+$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$CLIENTBOX_NEU+$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$WUNSCHIMAGE_NEU+$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi_masterbox+openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi-clientbox+openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS_PLUS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_REISER_FS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_PACKAGE_USBIDS_FORCE_DOWNLOAD $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		PUMA7_IMAGE="puma7"
		PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
		if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
		then
		sed -i "s+FREETZ_HOSTTOOLS_DOWNLOAD=y+# FREETZ_HOSTTOOLS_DOWNLOAD is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		fi
		##### test
		sed -i "s+FREETZ_PACKAGE_XZ=y+# FREETZ_PACKAGE_XZ is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_liblzma=y+# FREETZ_LIB_liblzma is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libz=y+# FREETZ_LIB_libz is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libelf=y+# FREETZ_LIB_libelf is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libltdl=y+# FREETZ_LIB_libltdl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX___V136_FEATURE_MD5_SHA1_SUM_CHECK=y+# FREETZ_BUSYBOX___V136_FEATURE_MD5_SHA1_SUM_CHECK is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
# Get custom image file name part from .config
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
#FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT)"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"
fi

if [ -z $PARAM_OSCAM_SMOD ]; then
		sleep 0
	else
		sed -i "s+FREETZ_LIB_libgcrypt=y+# FREETZ_LIB_libgcrypt is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libntfs=y+# FREETZ_LIB_libntfs is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libfuse=y+# FREETZ_LIB_libfuse is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_0=y+# FREETZ_LIB_libusb_0 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libnettle=y+# FREETZ_LIB_libnettle is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libftdi=y+# FREETZ_LIB_libftdi is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX_LSUSB=y+# FREETZ_BUSYBOX_LSUSB is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS=y+# FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libcrypto=y+# FREETZ_LIB_libcrypto is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libgpg_error=y+# FREETZ_LIB_libgpg_error is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_OSCAM=y+# FREETZ_PACKAGE_OSCAM is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_CCID=y+# FREETZ_PACKAGE_CCID is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_PCSC_LITE=y+# FREETZ_PACKAGE_PCSC_LITE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libpcsclite=y+# FREETZ_LIB_libpcsclite is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_1=y+# FREETZ_LIB_libusb_1 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBIDS=y+# FREETZ_PACKAGE_USBIDS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBUTILS=y+# FREETZ_PACKAGE_USBUTILS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_ftdi_sio=y+# FREETZ_MODULE_ftdi_sio is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_pl2303=y+# FREETZ_MODULE_pl2303 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_usbserial=y+# FREETZ_MODULE_usbserial is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_UDEVMOUNT=y+# FREETZ_PATCH_UDEVMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_MAXDEVCOUNT=y+# FREETZ_PATCH_MAXDEVCOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_CUSTOM_UDEV_RULES=y+# FREETZ_CUSTOM_UDEV_RULES is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_DROP_NOEXEC_EXTERNAL=y+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_FREETZMOUNT=y+# FREETZ_PATCH_FREETZMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_PORTFW=y+# FREETZ_PACKAGE_AVM_PORTFW is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FIREWALL=y+# FREETZ_PACKAGE_AVM_FIREWALL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FORWARDING=y+# FREETZ_PACKAGE_AVM_FORWARDING is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_STRACE=y+# FREETZ_PACKAGE_STRACE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v ${OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		sed -i "s+with_readerdriver_$MASTERBOX_NEU+$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$CLIENTBOX_NEU+$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$WUNSCHIMAGE_NEU+$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi_masterbox+openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi-clientbox+openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS_PLUS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_REISER_FS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_PACKAGE_USBIDS_FORCE_DOWNLOAD $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		PUMA7_IMAGE="puma7"
		PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
		if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
		then
		sed -i "s+FREETZ_HOSTTOOLS_DOWNLOAD=y+# FREETZ_HOSTTOOLS_DOWNLOAD is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		fi
# Get custom image file name part from .config
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
#FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT)"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"
fi

if [ -z $PARAM_OSCAM_NCAM ]; then
		sleep 0
	else
		sed -i "s+FREETZ_LIB_libgcrypt=y+# FREETZ_LIB_libgcrypt is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libntfs=y+# FREETZ_LIB_libntfs is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libfuse=y+# FREETZ_LIB_libfuse is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_0=y+# FREETZ_LIB_libusb_0 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libnettle=y+# FREETZ_LIB_libnettle is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libftdi=y+# FREETZ_LIB_libftdi is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX_LSUSB=y+# FREETZ_BUSYBOX_LSUSB is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS=y+# FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libcrypto=y+# FREETZ_LIB_libcrypto is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libgpg_error=y+# FREETZ_LIB_libgpg_error is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_OSCAM=y+# FREETZ_PACKAGE_OSCAM is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_CCID=y+# FREETZ_PACKAGE_CCID is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_PCSC_LITE=y+# FREETZ_PACKAGE_PCSC_LITE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libpcsclite=y+# FREETZ_LIB_libpcsclite is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_1=y+# FREETZ_LIB_libusb_1 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBIDS=y+# FREETZ_PACKAGE_USBIDS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBUTILS=y+# FREETZ_PACKAGE_USBUTILS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_ftdi_sio=y+# FREETZ_MODULE_ftdi_sio is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_pl2303=y+# FREETZ_MODULE_pl2303 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_usbserial=y+# FREETZ_MODULE_usbserial is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_UDEVMOUNT=y+# FREETZ_PATCH_UDEVMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_MAXDEVCOUNT=y+# FREETZ_PATCH_MAXDEVCOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_CUSTOM_UDEV_RULES=y+# FREETZ_CUSTOM_UDEV_RULES is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_DROP_NOEXEC_EXTERNAL=y+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_FREETZMOUNT=y+# FREETZ_PATCH_FREETZMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_PORTFW=y+# FREETZ_PACKAGE_AVM_PORTFW is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FIREWALL=y+# FREETZ_PACKAGE_AVM_FIREWALL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FORWARDING=y+# FREETZ_PACKAGE_AVM_FORWARDING is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_STRACE=y+# FREETZ_PACKAGE_STRACE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v ${OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		sed -i "s+with_readerdriver_$MASTERBOX_NEU+$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$CLIENTBOX_NEU+$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$WUNSCHIMAGE_NEU+$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi_masterbox+openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi-clientbox+openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS_PLUS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_REISER_FS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_PACKAGE_USBIDS_FORCE_DOWNLOAD $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		PUMA7_IMAGE="puma7"
		PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
		if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
		then
		sed -i "s+FREETZ_HOSTTOOLS_DOWNLOAD=y+# FREETZ_HOSTTOOLS_DOWNLOAD is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		fi
# Get custom image file name part from .config
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
#FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT)"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"
fi

if [ -z $PARAM_OSCAM_TOOL ]; then
		sleep 0
	else
		sed -i "s+FREETZ_LIB_libgcrypt=y+# FREETZ_LIB_libgcrypt is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libntfs=y+# FREETZ_LIB_libntfs is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libfuse=y+# FREETZ_LIB_libfuse is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_0=y+# FREETZ_LIB_libusb_0 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libnettle=y+# FREETZ_LIB_libnettle is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libftdi=y+# FREETZ_LIB_libftdi is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX_LSUSB=y+# FREETZ_BUSYBOX_LSUSB is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS=y+# FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libcrypto=y+# FREETZ_LIB_libcrypto is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libgpg_error=y+# FREETZ_LIB_libgpg_error is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_OSCAM=y+# FREETZ_PACKAGE_OSCAM is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_CCID=y+# FREETZ_PACKAGE_CCID is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_PCSC_LITE=y+# FREETZ_PACKAGE_PCSC_LITE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libpcsclite=y+# FREETZ_LIB_libpcsclite is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libusb_1=y+# FREETZ_LIB_libusb_1 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBIDS=y+# FREETZ_PACKAGE_USBIDS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_USBUTILS=y+# FREETZ_PACKAGE_USBUTILS is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_ftdi_sio=y+# FREETZ_MODULE_ftdi_sio is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_pl2303=y+# FREETZ_MODULE_pl2303 is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_MODULE_usbserial=y+# FREETZ_MODULE_usbserial is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_UDEVMOUNT=y+# FREETZ_PATCH_UDEVMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_MAXDEVCOUNT=y+# FREETZ_PATCH_MAXDEVCOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_CUSTOM_UDEV_RULES=y+# FREETZ_CUSTOM_UDEV_RULES is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_DROP_NOEXEC_EXTERNAL=y+# FREETZ_DROP_NOEXEC_EXTERNAL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PATCH_FREETZMOUNT=y+# FREETZ_PATCH_FREETZMOUNT is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_PORTFW=y+# FREETZ_PACKAGE_AVM_PORTFW is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FIREWALL=y+# FREETZ_PACKAGE_AVM_FIREWALL is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_AVM_FORWARDING=y+# FREETZ_PACKAGE_AVM_FORWARDING is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_LIB_libssl=y+# FREETZ_LIB_libssl is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+FREETZ_PACKAGE_STRACE=y+# FREETZ_PACKAGE_STRACE is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v ${OSCAM_ADDON_VERSION} $FREETZ_SSL_HOME_PATH/addon/static.pkg  > $FREETZ_SSL_HOME_PATH/addon/tempdatei && mv $FREETZ_SSL_HOME_PATH/addon/tempdatei $FREETZ_SSL_HOME_PATH/addon/static.pkg
		sed -i "s+with_readerdriver_$MASTERBOX_NEU+$MASTERBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$CLIENTBOX_NEU+$CLIENTBOX_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_$WUNSCHIMAGE_NEU+$WUNSCHIMAGE_NEU+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi_masterbox+openssl_multi_masterbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		sed -i "s+with_readerdriver_openssl_multi-clientbox+openssl_multi_clientbox+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_HFS_PLUS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_UDEVMOUNT_REISER_FS $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		grep -v FREETZ_PACKAGE_USBIDS_FORCE_DOWNLOAD $FREETZ_SSL_HOME_PATH/.config 2>/dev/null  > $FREETZ_SSL_HOME_PATH/tempdatei && mv $FREETZ_SSL_HOME_PATH/tempdatei $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		PUMA7_IMAGE="puma7"
		PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
		if [ $PUMA7_IMAGE_COMMENT = $PUMA7_IMAGE ] 2>/dev/null
		then
		sed -i "s+FREETZ_HOSTTOOLS_DOWNLOAD=y+# FREETZ_HOSTTOOLS_DOWNLOAD is not set+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
		fi
# Get custom image file name part from .config
FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
#FUD_COMMENT_BOX="$(echo $FUD_COMMENT | awk -F'_' '{print $NF}')"
FUD_COMMENT_BOX="$(echo $FUD_COMMENT)"
FUD_COMMENT_SSL="${FUD_COMMENT/"_${FUD_COMMENT_BOX}"/""}"
fi
