#!/bin/bash

# Function to comment out lines in the config file
comment_out_lines() {
	for line in "$@"; do
		sed -i "s+$line=y+# $line is not set+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
	done
		sed -i "s+oscam_${FUD_COMMENT_RD}+${FUD_COMMENT_RD}+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
}

# Lines to comment out
lines_to_comment=(
	"FREETZ_LIB_libgcrypt"
	"FREETZ_LIB_libssl"
	"FREETZ_LIB_libntfs"
	"FREETZ_LIB_libfuse"
	"FREETZ_LIB_libusb_0"
	"FREETZ_LIB_libnettle"
	"FREETZ_LIB_libftdi"
	"FREETZ_BUSYBOX_LSUSB"
	"FREETZ_BUSYBOX__NOEXEC_NOFORK_OPTIMIZATIONS"
	"FREETZ_LIB_libcrypto"
	"FREETZ_LIB_libgpg_error"
	"FREETZ_PACKAGE_OSCAM"
	"FREETZ_PACKAGE_CCID"
	"FREETZ_PACKAGE_PCSC_LITE"
	"FREETZ_LIB_libpcsclite"
	"FREETZ_LIB_libusb_1"
	"FREETZ_PACKAGE_USBIDS"
	"FREETZ_PACKAGE_USBUTILS"
	"FREETZ_MODULE_ftdi_sio"
	"FREETZ_MODULE_pl2303"
	"FREETZ_MODULE_usbserial"
	"FREETZ_PATCH_UDEVMOUNT"
	"FREETZ_PATCH_MAXDEVCOUNT"
	"FREETZ_CUSTOM_UDEV_RULES"
	"FREETZ_DROP_NOEXEC_EXTERNAL"
	"FREETZ_PATCH_FREETZMOUNT"
	"FREETZ_PACKAGE_AVM_PORTFW"
	"FREETZ_PACKAGE_AVM_FIREWALL"
	"FREETZ_PACKAGE_AVM_FORWARDING"
	"FREETZ_PACKAGE_STRACE"
	"FREETZ_PACKAGE_OPENSSL"
)

# Check each parameter
for param in "PARAM_OSCAM" "PARAM_OSCAM_EMU" "PARAM_OSCAM_SMOD" "PARAM_OSCAM_NCAM" "PARAM_OSCAM_TOOL"; do
	if [ -n "${!param}" ]; then
		comment_out_lines "${lines_to_comment[@]}"
		
		# Additional specific commands if needed
		grep -v "${OSCAM_ADDON_VERSION}" "$FREETZ_SSL_HOME_PATH/addon/static.pkg" > "$FREETZ_SSL_HOME_PATH/addon/tempdatei" && \
		mv "$FREETZ_SSL_HOME_PATH/addon/tempdatei" "$FREETZ_SSL_HOME_PATH/addon/static.pkg"
		
		# Handle custom image file name part
		FUD_COMMENT="$(grep '^FREETZ_USER_DEFINED_COMMENT=' "$FREETZ_SSL_HOME_PATH/.config" | awk -F'"' '{print $2}' | xargs)"
		FUD_COMMENT_BOX="$(echo "$FUD_COMMENT")"
		FUD_COMMENT_SSL="${FUD_COMMENT/_$FUD_COMMENT_BOX/}"
	fi
done
