#!/bin/bash

# Define the configuration file
CONFIG_FILE="$FREETZ_SSL_HOME_PATH/.config"

# Read necessary values
FUD_COMMENT_RD="$(grep '^FREETZ_USER_DEFINED_COMMENT=' .config | awk -F'"' '{print $2}' | xargs)"
PUMA7_IMAGE="puma7"
PUMA7_IMAGE_COMMENT="$(grep '^FREETZ_SYSTEM_TYPE=' .config | awk -F'"' '{print $2}' | xargs)"
# Update user-defined comment
sed -i "s+${FUD_COMMENT_RD}+oscam_${FUD_COMMENT_RD}+g" "$CONFIG_FILE" 2>/dev/null

# Array of configurations to enable
configs=(
	"FREETZ_PACKAGE_OSCAM"
	"FREETZ_PACKAGE_CCID"
	"FREETZ_PACKAGE_PCSC_LITE"
	"FREETZ_LIB_libpcsclite"
	"FREETZ_LIB_libusb_0"
	"FREETZ_LIB_libusb_1"
	"FREETZ_LIB_libftdi"
	"FREETZ_PACKAGE_USBIDS"
	"FREETZ_PACKAGE_USBUTILS"
	"FREETZ_MODULE_ftdi_sio"
	"FREETZ_MODULE_pl2303"
	"FREETZ_MODULE_usbserial"
	"FREETZ_PATCH_UDEVMOUNT"
	"FREETZ_PATCH_MAXDEVCOUNT"
	"FREETZ_CUSTOM_UDEV_RULES"
	"FREETZ_DROP_NOEXEC_EXTERNAL"
	"FREETZ_PATCH_FREETZMOUNT"
	"FREETZ_PACKAGE_AVM_FIREWALL"
	"FREETZ_PACKAGE_AVM_FORWARDING"
	"FREETZ_PACKAGE_STRACE"
	"FREETZ_REPLACE_KERNEL"
	"FREETZ_LIB_libssl"
)

# Enable necessary configurations
for config in "${configs[@]}"; do
	sed -i "s+# $config is not set+$config=y+g" "$CONFIG_FILE" 2>/dev/null
done
