#!/bin/bash
if [ -z $PARAM_CM ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/callmonitor_off
fi

if [ -z $PARAM_RR ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/rrdstats_off
	source $PKGS_PATH_ON_OFF/cifsmount_off
fi

if [ -z $PARAM_RR_1_8 ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/rrdstats_off
	source $PKGS_PATH_ON_OFF/cifsmount_off
fi

if [ -z $PARAM_USER_SCRIPTS ]; then
	sleep 0
else
	source $USER_APPLICATION_OFF
fi

if [ -z $PARAM_VNSTAT ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/vnstat_off
fi

if [ -z $PARAM_WIREGUARD ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/wireguard_off
fi

if [ -z $PARAM_OPENVPN ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/openvpn_off
fi

if [ -z $PARAM_TELNET ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/telnet_off
fi

if [ -z $PARAM_KEYPACK ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/key_pack_off
fi

if [ -z $PARAM_IDM ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/inadyn-mt_off
fi
