#!/bin/bash
if [ -z $PARAM_CM ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/callmonitor_on
fi

if [ -z $PARAM_RR ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/rrdstats_on
	source $PKGS_PATH_ON_OFF/cifsmount_on
fi
	
if [ -z $PARAM_RR_1_8 ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/rrdstats_1_8_on
	source $PKGS_PATH_ON_OFF/cifsmount_on
fi

if [ -z $PARAM_USER_SCRIPTS ]; then
	sleep 0
else
	ln -s $USER_APPLICATION_ON $I_MATIK_PATH/user-application_please_edit_me 2>/dev/null
	source $USER_APPLICATION_ON
fi
	
if [ -z $PARAM_VNSTAT ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/vnstat_on
fi
	
if [ -z $PARAM_WIREGUARD ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/wireguard_on
fi

if [ -z $PARAM_OPENVPN ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/openvpn_on
fi

if [ -z $PARAM_TELNET ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/telnet_on
fi

if [ -z $PARAM_KEYPACK ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/key_pack_on
fi

if [ -z $PARAM_IDM ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/inadyn-mt_on
fi

if [ -z $PARAM_L4L ]; then
	sleep 0
else
	source $PKGS_PATH_ON_OFF/l4l_on
fi

sed -i "s+FREETZ_TYPE_FIRMWARE_DETECT_LATEST=y+# FREETZ_TYPE_FIRMWARE_DETECT_LATEST is not set+g" $FREETZ_SSL_HOME_PATH/.config
