#!/bin/bash

# Define an array of package configurations to enable
packages=(
	"FREETZ_PACKAGE_RRDSTATS_CABLEMODEM"
	"FREETZ_PACKAGE_RRDSTATS_SEGMENTLOAD"
)

# Iterate over the packages and enable them in the config file
for package in "${packages[@]}"; do
	sed -i "s+# ${package} is not set+${package}=y+g" "$FREETZ_SSL_HOME_PATH/.config"
done
