#!/bin/bash
RRD_AUTO_CHECK="$(grep '^FREETZ_TYPE_PREFIX_SERIES_SUBDIR=' .config | awk -F'"' '{print $2}' | xargs)"

if [ $RRD_AUTO_CHECK = $RRD_AUTO ]
	then
source $PKGS_PATH_ON_OFF/rrdstats_off
source $PKGS_PATH_ON_OFF/cifsmount_off
source $PKGS_PATH_ON_OFF/rrdstats_1_8_on
source $PKGS_PATH_ON_OFF/cifsmount_on
fi
