#!/bin/bash
ed $FREETZ_SSL_HOME_PATH/addon/static.pkg <<EOF
/# Addons:/a
Digital_Eliteboard_Skin
Keywelt_Skin
Nachtfalke_old_Skin
Nachtfalke_Skin
.
wq
EOF
sed -i "s+# FREETZ_SKIN_newfreetz is not set+FREETZ_SKIN_newfreetz=y+g" $FREETZ_SSL_HOME_PATH/.config
sed -i "s+# FREETZ_SKIN_phoenix is not set+FREETZ_SKIN_phoenix=y+g" $FREETZ_SSL_HOME_PATH/.config
