#!/bin/bash
if [ -z $PARAM_SKINS ]; then
	sleep 0
else
	sed -i "s+# FREETZ_SKIN_newfreetz is not set+FREETZ_SKIN_newfreetz=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_SKIN_phoenix is not set+FREETZ_SKIN_phoenix=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_SKIN_cuma is not set+FREETZ_SKIN_cuma=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_DIGITAL_ELITEBOARD is not set+FREETZ_PACKAGE_SKIN_DIGITAL_ELITEBOARD=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_KEYWELT is not set+FREETZ_PACKAGE_SKIN_KEYWELT=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_NACHTFALKE is not set+FREETZ_PACKAGE_SKIN_NACHTFALKE=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_NACHTFALKE_OLD is not set+FREETZ_PACKAGE_SKIN_NACHTFALKE_OLD=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
fi

if [ -z $PARAM_SKINS1 ]; then
	sleep 0
else
	sed -i "s+# FREETZ_SKIN_newfreetz is not set+FREETZ_SKIN_newfreetz=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_SKIN_phoenix is not set+FREETZ_SKIN_phoenix=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_SKIN_cuma is not set+FREETZ_SKIN_cuma=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_PRISRAK is not set+FREETZ_PACKAGE_SKIN_PRISRAK=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_PACKAGE_SKIN_PRISRAK1 is not set+FREETZ_PACKAGE_SKIN_PRISRAK1=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
	sed -i "s+# FREETZ_TAGGING_PRISRAK is not set+FREETZ_TAGGING_PRISRAK=y+g" $FREETZ_SSL_HOME_PATH/.config 2>/dev/null
fi
