#!/bin/bash

# Function to enable features in the .config file
enable_feature() {
	local feature=$1
	sed -i "s+$feature is not set+$feature=y+g" "$FREETZ_SSL_HOME_PATH/.config"
}

# Enable specified TOR features
enable_feature "FREETZ_PACKAGE_TOR"
enable_feature "FREETZ_PACKAGE_TOR_GEOIP_V4"
enable_feature "FREETZ_PACKAGE_TOR_GEOIP_V6"
enable_feature "FREETZ_PACKAGE_TOR_STATIC"
