#!/bin/bash

# Function to disable features in the .config file
disable_feature() {
	local feature=$1
	sed -i "s+$feature=y+# $feature is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
}

# Function to remove lines containing a specific feature
remove_feature_line() {
	local feature=$1
	grep -v "$feature" "$FREETZ_SSL_HOME_PATH/.config" > "$FREETZ_SSL_HOME_PATH/tempdatei" && mv "$FREETZ_SSL_HOME_PATH/tempdatei" "$FREETZ_SSL_HOME_PATH/.config"
}

# Disable specified VSFTPD and library features
disable_feature "FREETZ_PACKAGE_VSFTPD"
disable_feature "FREETZ_LIB_libcrypto"
disable_feature "FREETZ_LIB_libcrypto_WITH_EC"
disable_feature "FREETZ_LIB_libssl"

# Remove lines for specified VSFTPD features
remove_feature_line "FREETZ_PACKAGE_VSFTPD_WITH_SSL"
remove_feature_line "FREETZ_PACKAGE_VSFTPD_STATIC"
