#!/bin/bash

# Disable VNStat-related packages in the configuration
sed -i "s+FREETZ_PACKAGE_VNSTAT_CGI=y+# FREETZ_PACKAGE_VNSTAT_CGI is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_PACKAGE_VNSTAT=y+# FREETZ_PACKAGE_VNSTAT is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_PACKAGE_VNSTAT_DAEMON=y+# FREETZ_PACKAGE_VNSTAT_DAEMON is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+FREETZ_PACKAGE_VNSTAT_IMAGE=y+# FREETZ_PACKAGE_VNSTAT_IMAGE is not set+g" "$FREETZ_SSL_HOME_PATH/.config"

# Update VNStat comments in the configuration
sed -i "s+vnstat_${FUD_COMMENT_VNSTAT}+${FUD_COMMENT_VNSTAT}+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
sed -i "s+vnstat_${FUD_COMMENT_RRD}+${FUD_COMMENT_RRD}+g" "$FREETZ_SSL_HOME_PATH/.config" 2>/dev/null
