#!/bin/bash

# Enable WireGuard package
sed -i "s+# FREETZ_PACKAGE_WIREGUARD is not set+FREETZ_PACKAGE_WIREGUARD=y+g" "$FREETZ_SSL_HOME_PATH/.config"

# Set user levels
sed -i "s+FREETZ_USER_LEVEL_EXPERT=y+# FREETZ_USER_LEVEL_EXPERT is not set+g" "$FREETZ_SSL_HOME_PATH/.config"
sed -i "s+# FREETZ_USER_LEVEL_DEVELOPER is not set+FREETZ_USER_LEVEL_DEVELOPER=y+g" "$FREETZ_SSL_HOME_PATH/.config"

# Append a comment for iptables if not already present
if ! grep -q '# FREETZ_PACKAGE_IPTABLES is not set' "$FREETZ_SSL_HOME_PATH/.config"; then
    sed -i '$a# FREETZ_PACKAGE_IPTABLES is not set' "$FREETZ_SSL_HOME_PATH/.config"
fi

# Enable iptables package
sed -i "s+# FREETZ_PACKAGE_IPTABLES is not set+FREETZ_PACKAGE_IPTABLES=y+g" "$FREETZ_SSL_HOME_PATH/.config"

# Source additional configurations
source "$I_MATIK_PATH/support/freetz/scripts/patches/friends/make/kernel/XTABLES" 2>/dev/null
