#!/bin/bash
#define freetz-ng for ssl path
FREETZ_PATH_SSL_10="$I_MATIK_PATH/freetz-ng"
FREETZ_PATH_SSL_11="$I_MATIK_PATH/freetz-ng"
FREETZ_PATH_SSL_30="$I_MATIK_PATH/freetz-ng"
FREETZ_PATH_SSL_31="$I_MATIK_PATH/freetz-ng"
FREETZ_PATH_SSL_MULTI="$I_MATIK_PATH/reetz-ng"

#define image home path
FREETZ_IMAGE_PATH="$I_MATIK_PATH/freetz-images"
END_IMAGE_PATH="images"
END_IMAGE_INMEMORY_PATH="image_inmemory"

#delete images that are older than 1440 mins (1Day)
DELETE_IMAGES="1440"

# Here you can specify the maximum threads on your CPU
MAX_CPUS="$(getconf _NPROCESSORS_ONLN)";

#define i-matik path for oscam
OSCAM_PATH="$I_MATIK_PATH/s3_releases"

#delete oscam that are older than 1440 mins (1Day)
DELETE_OSCAM="1440"
DELETE_OSCAM_LOG="15"

#define i-matik for oscam reader treiber
OSCAM_READER="webif-libusb-pcsc"
#OSCAM_READER="webif-dvbapi-libusb-pcsc"
#OSCAM_READER="webif-libusb-pcsc-ipv6"
#define i-matik for oscam reader treiber mit EMU
OSCAM_READER_EMU="webif-libusb-pcsc-emu"
#OSCAM_READER_EMU="webif-dvbapi-libusb-pcsc-emu"
#OSCAM_READER_EMU="webif-libusb-pcsc-ipv6-emu"

#Change network card settings
NETZWERK="enp69s0:0"

#to change the FREETZ_USER_DEFINED_COMMENT
MASTERBOX_ALT="openssl_1_0_x_masterbox" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
MASTERBOX_NEU="masterbox"

CLIENTBOX_ALT="openssl_1_0_x_clientbox" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
CLIENTBOX_NEU="clientbox"

POWERLINE_ALT="openssl_1_0_x_powerline" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
POWERLINE_NEU="powerline"

REPEATER_ALT="openssl_1_0_x_repeater" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
REPEATER_NEU="repeater"

GATEWAY_ALT="openssl_1_0_x_gateway" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
GATEWAY_NEU="gateway"

WUNSCHIMAGE_ALT="openssl_1_0_x_wunschimage" #HERE, WHEN CHANGING THE CURRENT NEW NAME MUST BE INCLUDED
WUNSCHIMAGE_NEU="wunschimage"

#this is where the self-built toolchains are stored
USER_OSCAM_TOOLCHAINS="$I_MATIK_PATH/support/s3_releases/USER_OSCAM_TOOLCHAINS"
#end of config
