#!/bin/bash
KERNEL="$(grep '^FREETZ_KERNEL_VERSION=' .config | awk -F'"' '{print $2}' | xargs)"
BAD1="4.1.38"
BAD2="4.4.271"
BAD3="4.9.218"
BAD4="4.19.183"

if [ $KERNEL = $BAD1 ]
	then
		source $I_MATIK_PATH/support/freetz/scripts/packages/oscam_off
elif [ $KERNEL = $BAD2 ]
	then
		source $I_MATIK_PATH/support/freetz/scripts/packages/oscam_off
elif [ $KERNEL = $BAD3 ]
	then
		source $I_MATIK_PATH/support/freetz/scripts/packages/oscam_off
elif [ $KERNEL = $BAD4 ]
	then
		source $I_MATIK_PATH/support/freetz/scripts/packages/oscam_off
	fi
