#!/bin/bash
if [[ "$KERNEL" == "$BAD_KERNEL1" || "$KERNEL" == "$BAD_KERNEL2" || "$KERNEL" == "$BAD_KERNEL3" || "$KERNEL" == "$BAD_KERNEL4" ]]; then
	[ -f .config_backup ] && mv .config_backup .config  # Rename backup config to original config

	# End point: show how long it took to create the images
	finish=$(date +"%s")	# Script finished time
	timediff=$(($finish - $begin))  # Script time
	avg=$(($timediff / $COUNT))	   # Average time per box
	printf "\nBuild time was $(($timediff / 60)) minutes and $(($timediff % 60)) seconds for ${COUNT} box(es). -> $(($avg / 60))m $(($avg % 60))s per box\n"
	$VERSION  # Show i-matik disclaimer
	sed -i "s+${VERSIONS_NR}+xxxxx+g" $VERSION  # Update version number
	exit
fi
