#!/bin/bash
SYSTEM_TYPE="$(grep '^FREETZ_AVM_SOURCE_FOR_SYSTEM_TYPE_' .config | awk -F'=y' '{print $1}' | xargs | tr '[:upper:]' '[:lower:]')"
SOURCE_ID="$(grep '^FREETZ_AVM_SOURCE_ID=' .config | awk -F'"' '{print $2}' | xargs)"
CORE_SUFFIX="$(grep '^FREETZ_SYSTEM_TYPE_CORE_SUFFIX=' .config | awk -F'"' '{print $2}' | xargs)"

cp -p $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}.orig 2>/dev/null

#USB_HOST="y"
#USB_HOST_COMMENT="$(grep '^FREETZ_AVM_HAS_USB_HOST=' .config | awk -F'"' '{print $1}' | xargs)"
#if [ ${USB_HOST_COMMENT:24:1} = $USB_HOST ] 2>/dev/null
#then
sed -i "s+# CONFIG_USB_SERIAL is not set+CONFIG_USB_SERIAL=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_USB_SERIAL_FTDI_SIO is not set+CONFIG_USB_SERIAL_FTDI_SIO=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_USB_SERIAL_PL2303 is not set+CONFIG_USB_SERIAL_PL2303=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
#fi
sed -i "s+# CONFIG_AUTOFS4_FS is not set+CONFIG_AUTOFS4_FS=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_NETWORK_FILESYSTEMS is not set+CONFIG_NETWORK_FILESYSTEMS=y+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_CRYPTO_ARC4 is not set+CONFIG_CRYPTO_ARC4=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_FUSE_FS is not set+CONFIG_FUSE_FS=y+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_CRYPTO_CMAC is not set+CONFIG_CRYPTO_CMAC=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_CRYPTO_HMAC is not set+CONFIG_CRYPTO_HMAC=y+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_PPP is not set+CONFIG_PPP=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_CRYPTO_SHA1 is not set+CONFIG_CRYPTO_SHA1=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_TUN is not set+CONFIG_TUN=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
sed -i "s+# CONFIG_CRYPTO_MD4 is not set+CONFIG_CRYPTO_MD4=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
#sed -i "s+CONFIG_BLK_DEV_LOOP=y+CONFIG_BLK_DEV_LOOP=m+g" $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null

grep -v CONFIG_NFS_FS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_V2 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_V3 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_V3_ACL $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_V4 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_SWAP $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_ROOT_NFS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFSD $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFSD_DEPRECATED $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFSD_V3 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFSD_V3_ACL $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFSD_V4 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_GRACE_PERIOD $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_LOCKD $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_LOCKD_V4 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NFS_COMMON $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_SUNRPC $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_SUNRPC_DEBUG $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_SUNRPC_REGISTER_V4 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CEPH_FS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_STATS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_STATS2 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_WEAK_PW_HASH $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_UPCALL $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_XATTR $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_DEBUG $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_DEBUG2 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_DFS_UPCALL $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_SMB2 $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_NCP_FS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CODA_FS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_AFS_FS $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CUSE $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null
grep -v CONFIG_CIFS_EXPERIMENTAL $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID}  > $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei && mv $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/tempdatei $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} 2>/dev/null

ed $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} <<EOF
/# CONFIG_NETWORK_FILESYSTEMS is not set/a
CONFIG_NFS_FS=m
CONFIG_NFS_V2=m
CONFIG_NFS_V3=m
CONFIG_NFS_V3=y
# CONFIG_NFS_V3_ACL is not set
# CONFIG_NFS_V4 is not set
# CONFIG_NFS_SWAP is not set
CONFIG_ROOT_NFS=y
CONFIG_NFSD=m
CONFIG_NFSD_V2_ACL=y
CONFIG_NFSD_V3=y
CONFIG_NFSD_V3_ACL=y
CONFIG_NFSD_V4=y
# CONFIG_NFSD_DEPRECATED is not set
CONFIG_GRACE_PERIOD=m
CONFIG_LOCKD=m
CONFIG_LOCKD_V4=y
CONFIG_NFS_COMMON=y
CONFIG_SUNRPC=m
CONFIG_SUNRPC=y
CONFIG_SUNRPC_REGISTER_V4=y
# CONFIG_SUNRPC_DEBUG is not set
# CONFIG_CEPH_FS is not set
CONFIG_CIFS=m
CONFIG_CIFS_STATS=y
# CONFIG_CIFS_STATS2 is not set
# CONFIG_CIFS_WEAK_PW_HASH is not set
# CONFIG_CIFS_UPCALL is not set
# CONFIG_CIFS_XATTR is not set
CONFIG_CIFS_DEBUG=y
# CONFIG_CIFS_DEBUG2 is not set
# CONFIG_CIFS_DFS_UPCALL is not set
# CONFIG_CIFS_EXPERIMENTAL is not set
# CONFIG_CIFS_SMB2 is not set
# CONFIG_NCP_FS is not set
# CONFIG_CODA_FS is not set
# CONFIG_AFS_FS is not set
.
wq
EOF
ed $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} <<EOF
/CONFIG_NETWORK_FILESYSTEMS=y/a
CONFIG_NFS_FS=m
CONFIG_NFS_V2=m
CONFIG_NFS_V3=m
CONFIG_NFS_V3=y
# CONFIG_NFS_V3_ACL is not set
# CONFIG_NFS_V4 is not set
# CONFIG_NFS_SWAP is not set
CONFIG_ROOT_NFS=y
CONFIG_NFSD=m
CONFIG_NFSD_V2_ACL=y
CONFIG_NFSD_V3=y
CONFIG_NFSD_V3_ACL=y
CONFIG_NFSD_V4=y
# CONFIG_NFSD_DEPRECATED is not set
CONFIG_GRACE_PERIOD=m
CONFIG_LOCKD=m
CONFIG_LOCKD_V4=y
CONFIG_NFS_COMMON=y
CONFIG_SUNRPC=m
CONFIG_SUNRPC=y
CONFIG_SUNRPC_REGISTER_V4=y
# CONFIG_SUNRPC_DEBUG is not set
# CONFIG_CEPH_FS is not set
CONFIG_CIFS=m
CONFIG_CIFS_STATS=y
# CONFIG_CIFS_STATS2 is not set
# CONFIG_CIFS_WEAK_PW_HASH is not set
# CONFIG_CIFS_UPCALL is not set
# CONFIG_CIFS_XATTR is not set
CONFIG_CIFS_DEBUG=y
# CONFIG_CIFS_DEBUG2 is not set
# CONFIG_CIFS_DFS_UPCALL is not set
# CONFIG_CIFS_EXPERIMENTAL is not set
# CONFIG_CIFS_SMB2 is not set
# CONFIG_NCP_FS is not set
# CONFIG_CODA_FS is not set
# CONFIG_AFS_FS is not set
.
wq
EOF

ed $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} <<EOF
/CONFIG_FUSE_FS=y/a
# CONFIG_CUSE is not set
.
wq
EOF

ed $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} <<EOF
/CONFIG_FUSE_FS=m/a
# CONFIG_CUSE is not set
.
wq
EOF

ed $FREETZ_SSL_HOME_PATH/make/kernel/configs/freetz/config-${SYSTEM_TYPE:34:40}${CORE_SUFFIX}-${SOURCE_ID} <<EOF
/CONFIG_PPP=m/a
# CONFIG_PPP_BSDCOMP is not set
CONFIG_PPP_DEFLATE=m
# CONFIG_PPP_FILTER is not set
CONFIG_PPP_MPPE=m
# CONFIG_PPP_MULTILINK is not set
# CONFIG_PPPOATM is not set
# CONFIG_PPPOE is not set
# CONFIG_PPPOL2TP is not set
CONFIG_PPP_ASYNC=m
# CONFIG_PPP_SYNC_TTY is not set
# CONFIG_SLIP is not set
CONFIG_SLHC=m
.
wq
EOF
