#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bind/bind.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bind/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bind/bind.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bind/bind.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bind/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bind/Config.in 2>/dev/null
