#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/bittwist.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/patches/100_ifaddrs_SIOCGIFHWADDR.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/bittwist.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/bittwist.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.files.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/external.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/patches/100_ifaddrs_SIOCGIFHWADDR.patch.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/patches/100_ifaddrs_SIOCGIFHWADDR.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/patches/110-Makefile.patch.orig $FREETZ_SSL_HOME_PATH/make/pkgs/bittwist/patches/110-Makefile.patch 2>/dev/null
