#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH//make/ca-bundle/ca-bundle.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/mmake/ca-bundle/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH//make/ca-bundle/ca-bundle.mk.orig $FREETZ_SSL_HOME_PATH//make/ca-bundle/ca-bundle.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/ca-bundle/Config.in.orig $FREETZ_SSL_HOME_PATH/make/ca-bundle/Config.in 2>/dev/null
