#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/ccid.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/ccid.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/ccid.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/ccid/Config.in 2>/dev/null
