#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk.orig $FREETZ_SSL_HOME_PATH/make/cifsmount/cifsmount.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in.orig $FREETZ_SSL_HOME_PATH/make/cifsmount/Config.in 2>/dev/null
