#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/dbus.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/Config.in 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.files 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.in.libs 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/010-link_all_deplibs.patch 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/020-drop_backtrace_dependency.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/dbus.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/dbus.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.files.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.files 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.in.libs.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/external.in.libs 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/010-link_all_deplibs.patch.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/010-link_all_deplibs.patch 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/020-drop_backtrace_dependency.patch.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dbus/patches/020-drop_backtrace_dependency.patch 2>/dev/null
