#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/dtach.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/dtach.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/dtach.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/dtach/Config.in 2>/dev/null
