#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk.orig $FREETZ_SSL_HOME_PATH/make/pcsc-lite/pcsc-lite.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pcsc-lite/Config.in 2>/dev/null

