#!/bin/bash
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/tor/tor.mk 2>/dev/null
rm -f $FREETZ_SSL_HOME_PATH/make/pkgs/tor/Config.in 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/tor/tor.mk.orig $FREETZ_SSL_HOME_PATH/make/pkgs/tor/tor.mk 2>/dev/null
mv $FREETZ_SSL_HOME_PATH/make/pkgs/tor/Config.in.orig $FREETZ_SSL_HOME_PATH/make/pkgs/tor/Config.in 2>/dev/null
